name: Publicação automática
on: 
  # nosso script será executado sempre quando houver push nas branches destacadas abaixo
  push:
    branches: [ "main" ]

jobs:
  build:
    # sistema operacional da máquina que o Github irá disponibilizar para rodar o nosso script
    runs-on: ubuntu-latest

    # aqui é iniciado o passo a passo para realizar o processo de publicação
    steps:
      - uses: actions/checkout@v3

      - name: Cria um arquivo temporário para a chave privada e altera a permissão do arquivo para que só o dono possa ler e escrever (necessário para chaves)
        run: |
          echo "${{ secrets.KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key

      - name: Realizar backup da aplicação antes da substituição
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
          "DATA=\$(date +%Y%m%d_%H%M%S) && if [ -d '/home/ubuntu/appdemo1' ]; then sudo cp -r /home/ubuntu/appdemo1 /home/ubuntu/appdemo1_bkp_\$DATA; fi"

      - name: Criando a pasta da aplicação e acertando diretório... 
        # StrictHostKeyChecking: desativar prompt 'fingerprint'
        # UserKnownHostsFile: para não salvar a chave
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
          sudo mkdir -p /home/ubuntu/appdemo1

      - name: Ajustar permissões no servidor de Produção
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} "sudo chown -R ubuntu:ubuntu /home/ubuntu/appdemo1 && sudo chmod -R 755 /home/ubuntu/appdemo1"
                  
      - name: Transferindo os arquivos da aplicação
        run: |
          scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${{ github.workspace }}/* ubuntu@${{ secrets.HOST }}:/home/ubuntu/appdemo1

      - name: Reiniciando o serviço da aplicação
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
          sudo systemctl restart pythonweb.service             

      - name: Limpa o arquivo de chave privada após uso
        run: |
          rm /tmp/private_key

      - name: Notificar sucesso pelo Discord
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"content":"Deploy realizado com sucesso!"}' \
            ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notificar erro pelo Discord
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"content":"Erro ao realizar o deploy!"}' \
            ${{ secrets.DISCORD_WEBHOOK }}
